### ISSUE TITLE
MIDI versions of patterns

### ISSUE THREAD

**Issue by danielmroczek** [jcelerier/drum-patterns#1]
Is there any easy way to convert your PAT files into MIDI files? Maybe some automatic tool?

EDIT 2024-11-29:
So i created this tool myself, available here: [pat2midi](https://github.com/pan-danio/pat2midi).

**Comment by jcelerier** [comment]
heya ! fyi I noticed a few bugs in the patterns (some note names had been left untranslated, semi-open hi-hat and cowbell). Slide has been renamed to SL instead of SH which clears the confusion. This way these patterns will also be useable for TB 303 patterns.

**Comment by danielmroczek** [comment]
Thx for the info. I will implement SLide soon in my project. In drum patterns it has no sense, but since it support tb303 (and other synths) i will add that. Also i wanna note, that i worked on second part of René-Pierre Bardet's book called _260 Drum Machine Patterns_ and wanted to transcribe it to PAT (and then to MIDI) . He introduced there a "Flam" hit for drum (double stroke), so i thought that your PAT spec should also support that. Instead of 'normal' stroke represented by 'x', a "flam stroke" should be possible by "f".

**Comment by jcelerier** [comment]
sounds good !

**Comment by jcelerier** [comment]
yes, tb303 came here as scope creep aha, in the end I guess it would be a general "pattern-based sequence" format

**Comment by danielmroczek** [comment]
Thanks for quick response and edit! Already made use of that - i created PR with "260" drum patterns which use new "flam" stroke.
